// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.6
// source: rocksdb/rocksdb.proto

package rocksdb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RocksDBService_Put_FullMethodName           = "/rocksdb.RocksDBService/Put"
	RocksDBService_Get_FullMethodName           = "/rocksdb.RocksDBService/Get"
	RocksDBService_Delete_FullMethodName        = "/rocksdb.RocksDBService/Delete"
	RocksDBService_BatchPut_FullMethodName      = "/rocksdb.RocksDBService/BatchPut"
	RocksDBService_Scan_FullMethodName          = "/rocksdb.RocksDBService/Scan"
	RocksDBService_ScanPaginated_FullMethodName = "/rocksdb.RocksDBService/ScanPaginated"
	RocksDBService_RangeQuery_FullMethodName    = "/rocksdb.RocksDBService/RangeQuery"
	RocksDBService_Ping_FullMethodName          = "/rocksdb.RocksDBService/Ping"
	RocksDBService_Health_FullMethodName        = "/rocksdb.RocksDBService/Health"
)

// RocksDBServiceClient is the client API for RocksDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type RocksDBServiceClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Response, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error)
	BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*Response, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	ScanPaginated(ctx context.Context, in *ScanPaginatedRequest, opts ...grpc.CallOption) (*ScanPaginatedResponse, error)
	RangeQuery(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*RangeQueryResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*Response, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*Response, error)
}

type rocksDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRocksDBServiceClient(cc grpc.ClientConnInterface) RocksDBServiceClient {
	return &rocksDBServiceClient{cc}
}

func (c *rocksDBServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RocksDBService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocksDBServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, RocksDBService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocksDBServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RocksDBService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocksDBServiceClient) BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RocksDBService_BatchPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocksDBServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, RocksDBService_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocksDBServiceClient) ScanPaginated(ctx context.Context, in *ScanPaginatedRequest, opts ...grpc.CallOption) (*ScanPaginatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanPaginatedResponse)
	err := c.cc.Invoke(ctx, RocksDBService_ScanPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocksDBServiceClient) RangeQuery(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*RangeQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeQueryResponse)
	err := c.cc.Invoke(ctx, RocksDBService_RangeQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocksDBServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RocksDBService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocksDBServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RocksDBService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RocksDBServiceServer is the server API for RocksDBService service.
// All implementations must embed UnimplementedRocksDBServiceServer
// for forward compatibility
//
// Service definition
type RocksDBServiceServer interface {
	Put(context.Context, *PutRequest) (*Response, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*Response, error)
	BatchPut(context.Context, *BatchPutRequest) (*Response, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	ScanPaginated(context.Context, *ScanPaginatedRequest) (*ScanPaginatedResponse, error)
	RangeQuery(context.Context, *RangeQueryRequest) (*RangeQueryResponse, error)
	Ping(context.Context, *PingRequest) (*Response, error)
	Health(context.Context, *HealthRequest) (*Response, error)
	mustEmbedUnimplementedRocksDBServiceServer()
}

// UnimplementedRocksDBServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRocksDBServiceServer struct {
}

func (UnimplementedRocksDBServiceServer) Put(context.Context, *PutRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedRocksDBServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRocksDBServiceServer) Delete(context.Context, *DeleteRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRocksDBServiceServer) BatchPut(context.Context, *BatchPutRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPut not implemented")
}
func (UnimplementedRocksDBServiceServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedRocksDBServiceServer) ScanPaginated(context.Context, *ScanPaginatedRequest) (*ScanPaginatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanPaginated not implemented")
}
func (UnimplementedRocksDBServiceServer) RangeQuery(context.Context, *RangeQueryRequest) (*RangeQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RangeQuery not implemented")
}
func (UnimplementedRocksDBServiceServer) Ping(context.Context, *PingRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRocksDBServiceServer) Health(context.Context, *HealthRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRocksDBServiceServer) mustEmbedUnimplementedRocksDBServiceServer() {}

// UnsafeRocksDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RocksDBServiceServer will
// result in compilation errors.
type UnsafeRocksDBServiceServer interface {
	mustEmbedUnimplementedRocksDBServiceServer()
}

func RegisterRocksDBServiceServer(s grpc.ServiceRegistrar, srv RocksDBServiceServer) {
	s.RegisterService(&RocksDBService_ServiceDesc, srv)
}

func _RocksDBService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocksDBService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocksDBService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocksDBService_BatchPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).BatchPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_BatchPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).BatchPut(ctx, req.(*BatchPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocksDBService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocksDBService_ScanPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanPaginatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).ScanPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_ScanPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).ScanPaginated(ctx, req.(*ScanPaginatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocksDBService_RangeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).RangeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_RangeQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).RangeQuery(ctx, req.(*RangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocksDBService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocksDBService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocksDBServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RocksDBService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocksDBServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RocksDBService_ServiceDesc is the grpc.ServiceDesc for RocksDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RocksDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rocksdb.RocksDBService",
	HandlerType: (*RocksDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _RocksDBService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RocksDBService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RocksDBService_Delete_Handler,
		},
		{
			MethodName: "BatchPut",
			Handler:    _RocksDBService_BatchPut_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _RocksDBService_Scan_Handler,
		},
		{
			MethodName: "ScanPaginated",
			Handler:    _RocksDBService_ScanPaginated_Handler,
		},
		{
			MethodName: "RangeQuery",
			Handler:    _RocksDBService_RangeQuery_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _RocksDBService_Ping_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RocksDBService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rocksdb/rocksdb.proto",
}
